Medicines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

app_name = 'api'


urlpatterns = [
    path('medicines/', views.MedicinesListCreateView.as_view(), name='index'),
    path('medicine/<int:pk>/', views.MedicineRetrieveView.as_view(), name='medicine_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_change/', views.cart_change, name='cart_change'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.index, name='index'),
    path('store/', views.store, name='store'),
    path('medicine/<int:id>/', views.medicine_page, name='medicine_page'),
]

main/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name


class Form(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'form'
        verbose_name = 'Форма випуску'
        verbose_name_plural = 'Форми випуску'

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'manufacturer'
        verbose_name = 'Виробник'
        verbose_name_plural = 'Виробники'

    def __str__(self):
        return self.name


class CountryOfOrigin(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'country'
        verbose_name = 'Країна'
        verbose_name_plural = 'Країни'

    def __str__(self):
        return self.name


class Medicine(models.Model):
    name = models.CharField(max_length=100, help_text="Назва препарату")
    price = models.FloatField(help_text="Ціна", default=0, blank=True)
    photo = models.ImageField(upload_to='medicines_photos', help_text="Фото препарату", default='', blank=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, help_text="Категорія препарату (протизастудні, знеболюючі і т.д.)", blank=True, null=True)
    form = models.ForeignKey(Form, on_delete=models.DO_NOTHING, help_text="Форма випуску препарату (сироп, таблетки і т.д.)", blank=True, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.DO_NOTHING, help_text="Виробник препарату", blank=True, null=True)
    country_of_origin = models.ForeignKey(CountryOfOrigin, on_delete=models.DO_NOTHING, help_text="Країна-виробник", blank=True, null=True)
    is_prescription_required = models.BooleanField(default=False, help_text="Чи потрібен рецепт для покупки (Так/Ні)", blank=True)
    date_of_manufacture = models.DateField(help_text="Дата виготовлення", default='2001-01-01', blank=True)
    service_life = models.IntegerField(help_text="Термін придатності (в місяцях)", default=0, blank=True)
    description = models.TextField(help_text="Опис", default='', blank=True)
    quantity = models.IntegerField(help_text="Кількість препарату", default=0, blank=True)

    @classmethod
    def filter_medicines(cls, search, price_range, category, form, country, prescription, order_by):
        return cls.objects.filter(name__icontains=search,
                                  price__range=price_range,
                                  category__in=category,
                                  form__in=form,
                                  country_of_origin__in=country,
                                  is_prescription_required__in=prescription
                                  ).order_by(order_by)

    class Meta:
        db_table = 'medicine'
        verbose_name = 'Препарат'
        verbose_name_plural = 'Препарати'

    def __str__(self):
        return f'{self.name}'

main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .services import add_comment, delete_comment, get_all_comments_about_medicine, search_medicines, get_info_for_filters, search_medicine_by_id
from users.services import add_to_favourites


def index(request):
    return redirect('store:store')


def store(request):
    if request.POST:
        add_to_favourites(request.POST.get('username'), request.POST.get('medicine_id'))
        return redirect(request.POST.get('url'))

    medicines = search_medicines(request)
    medicines['filters'] = get_info_for_filters(medicines['medicines'])
    context = medicines
    context['title'] = 'Головна'

    return render(request, 'store/store.html', context)


def medicine_page(request, id):
    medicine = search_medicine_by_id(id=id)
    if not medicine['medicine']:
        return JsonResponse({'message': 'Not a valid ID'}, status=404)
    
    if request.POST:
        if request.POST.get('is_delete_comment'):
            delete_comment(request.POST.get('comment_id'))
        else:
            add_comment(request.POST.get('username'), medicine['medicine'], request.POST.get('comment'))

        return redirect(request.POST.get('url'))
    
    context = medicine
    context['title'] = medicine['medicine'].name
    context['comments'] = get_all_comments_about_medicine(medicine['medicine'])

    return render(request, 'store/medicine.html', context)

main/templates/includes/buttons_block_for_medicine.html
<div class="buy-favourites-buttons-block">
    <form method="POST" action="{% url 'cart:cart_change' %}" class="add-to-cart-form">
        {% csrf_token %}
        <input type="hidden" name="username" value="{{ user.username }}">
        <input type="hidden" name="medicine_id" value="{{ p.id }}">
        <input type="hidden" name="url" value="{{ request.build_absolute_uri }}">
        <input id="add-to-cart-button-{{ p.id }}" class="add-to-cart-button" type="submit" onclick="event.stopPropagation();" value="В корзину">
    </form>
    <form method="POST" action="{% url 'store:store' %}" class="add-to-favourites-form">
        {% csrf_token %}
        <input type="hidden" name="username" value="{{ user.username }}">
        <input type="hidden" name="medicine_id" value="{{ p.id }}">
        <input type="hidden" name="url" value="{{ request.build_absolute_uri }}">
        <input id="add-to-favourites-button-{{ p.id }}" class="add-to-favourites-button" type="submit" onclick="event.stopPropagation();" value="До улюблених">
    </form>
</div>

main/templates/includes/medicine.html
<div class='medicine' onclick="location.href='{% url 'store:medicine_page' id=p.id %}';">
    <img src="{% if 'https%3A/' in p.photo.url %}{{ p.photo }}{% else %}{{ p.photo.url }}{% endif %}" alt="{{ p.name }}" width="175" height="175"/> <br>
    <label style='font-weight: 450;'>{{ p.name }}</label> <br><br>
    <label style='font-size: 17px; font-weight: 600;'>{{ p.price }} грн</label>
    {% if user.is_authenticated %}
        {% if 'profile' in request.path %}
            {% if user == user_info %}
                {% include 'includes/buttons_block_for_medicine.html' %}
            {% endif %}
        {% else %}
            {% include 'includes/buttons_block_for_medicine.html' %}
        {% endif %}
    {% endif %}
</div>