Medicines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

app_name = 'api'


urlpatterns = [
    path('medicines/', views.MedicinesListCreateView.as_view(), name='index'),
    path('medicine/<int:pk>/', views.MedicineRetrieveView.as_view(), name='medicine_detail'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from main.models import Medicine


class User(AbstractUser):
    favourites = models.ManyToManyField(Medicine, help_text='Вибрані товари', blank=True)
    cart = models.ManyToManyField(Medicine, help_text='Товари в корзині', blank=True, related_name='cart')
    photo = models.ImageField(upload_to='users_photos', help_text="Фото користувача", default='static_photos/default_profile_photo.jpg', blank=True)

    def get_fav_list(self):
        return [fav.id for fav in self.favourites.all()]

    def get_cart_list(self):
        return [cart.id for cart in self.cart.all()]

    class Meta:
        db_table = 'user'
        verbose_name = 'Користувач'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return self.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, help_text='Користувач', blank=True, null=True)
    medicine = models.ForeignKey(Medicine, help_text='Препарат', on_delete=models.CASCADE)
    comment = models.TextField(help_text='Коментарій', blank=True)
    date_posted = models.DateTimeField(help_text='Дата', default=timezone.now)

    class Meta:
        db_table = 'comment'
        verbose_name = 'Коментарій'
        verbose_name_plural = 'Коментарі'

    def __str__(self):
        return f'Коментарій користувача {self.user} про препарат {self.medicine}'

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    photo = forms.ImageField(required=False)
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'photo',
        ]

users/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib import auth
from django.urls import reverse
from users.forms import UserLoginForm, UserProfileForm, UserSignupForm
from django.contrib.auth.decorators import login_required
from users.models import User


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                if request.POST.get('next'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('store:store'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизація',
        'form': form,
    }

    return render(request, 'users/login.html', context)


def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('store:store'))
    else:
        form = UserSignupForm()
    
    context = {
        'title': 'Реєстрація',
        'form': form,
    }

    return render(request, 'users/signup.html', context)


@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    if not user:
        return JsonResponse({'message': 'Not a valid username'}, status=404)

    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile', kwargs={'username': user.username}))
    else:
        form = UserProfileForm(instance=request.user)

    context = {
        'user_info': user,
        'title': user.username,
        'form': form,
    }

    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('store:store'))

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/users/signup.css' %}">

<div class="container">
    <div class="login form">
        <header>Вхід</header>
        <form action="{% url "user:login" %}" method="post">
            {% csrf_token %}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            {% if form.non_field_errors %}
                <p>{{ form.non_field_errors }}</p>
            {% endif %}
            <input type="text" name="username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" placeholder="Введіть логін" required>
            <input type="password" name="password" placeholder="Введіть пароль" required>
            <a href="#">Забули пароль?</a>
            <input type="submit" class="button" value="Увійти">
        </form>
        <div class="signup">
            <span class="signup">Не маєте аккаунту?
            <a href={% url 'user:signup' %}>Реєстрація</a>
            </span>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="user-info">
    <img src="{% if 'https%3A/' in user_info.photo.url %}{{ user_info.photo }}{% else %}{{ user_info.photo.url }}{% endif %}" alt="{{ user_info.username }}_photo" width="210" height="210"/>
    <h2 class='username-in-profile'>{{ user_info.username }}</h2>
    {% if user == user_info %}
    <form action="{% url 'user:profile' username=user_info.username %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="first_name">Ім'я:</label>
        <input type="text" id="first_name" style="left: 70px;" name="first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"><br>
        <label for="last_name">Прізвище:</label>
        <input type="text" id="last_name" style="left: 23px;" name="last_name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"><br>
        <label for="email">email:</label>
        <input type="text" id="email" style="left: 58px;" name="email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}"><br>
        {% if form.email.errors %}
            {{ form.email.errors }}
        {% endif %}
        <label for="profile_photo">Фото профілю:</label>
        <input type="file" id="profile_photo" name="photo"><br>
        <input type="submit" value="Зберегти">
    </form>
    {% endif %}
</div>
<div class="user-favourites-info">
    <p>Вибране:</p>
    <div>
    {% for p in user_info.favourites.all %}
        {% include 'includes/medicine.html' %}
    {% endfor %}
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/users/signup.css' %}">

<div class="container">
    <div class="registration form">
        <header>Реєстрація</header>
        <form action="{% url 'user:signup' %}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Введіть логін" name="username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" required>
            {% if form.username.errors %}{{ form.username.errors }}{% endif %}
            <input type="password" placeholder="Створіть пароль" name="password1" required>
            {% if form.password1.errors %}{{ form.password1.errors }}{% endif %}
            <input type="password" placeholder="Підтвердіть пароль" name="password2" required>
            {% if form.password2.errors %}{{ form.password2.errors }}{% endif %}
            <input type="submit" class="button" value="Реєстрація">
        </form>
        <div class="signup">
            <span class="signup">Вже маєте аккаунт?
            <a href={% url 'user:login' %}>Увійти</a>
            </span>
        </div>
    </div>
</div>
{% endblock %}