Medicines/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='store')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('api/', include('api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views

app_name = 'api'


urlpatterns = [
    path('medicines/', views.MedicinesListCreateView.as_view(), name='index'),
    path('medicine/<int:pk>/', views.MedicineRetrieveView.as_view(), name='medicine_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('cart_change/', views.cart_change, name='cart_change'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'store'


urlpatterns = [
    path('', views.index, name='index'),
    path('store/', views.store, name='store'),
    path('medicine/<int:id>/', views.medicine_page, name='medicine_page'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'


urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/base.css' %}">
    <link rel="stylesheet" href="{% static '/store/store.css' %}">
    <link rel="stylesheet" href="{% static '/store/medicine.css' %}">
    <link rel="stylesheet" href="{% static '/users/profile.css' %}">
    <script src="{% static '/scripts.js' %}"></script>
</head>
<body>
    <header class="header-store">
        <a href="{% url 'store:store' %}" class="medicines-label">Medicines</a>
        <div class="user-block">
            {% if user.is_authenticated %}
                <a class="username" href="{% url 'user:profile' username=user.username %}">{{ user.username }}</a>
                <input class='user-button' type='button' value='Вийти' onclick="window.location.href = '{% url 'user:logout' %}';">
                <input class='user-button' type='button' value='Корзина' onclick="window.location.href =  '{% url 'cart:cart' %}';">
            {% else %}
                <input class='user-button' type='button' value='Увійти' onclick="window.location.href = '{% url 'user:login' %}';">
            {% endif %}
            {% if user.is_admin or user.is_staff or user.is_superuser %}
                <input class='user-button' type='button' value='Адмін. панель' onclick="window.location.href = '{% url 'admin:index' %}';">
            {% endif %}
        </div>
    </header>
    <main>
        {% block content %}{% endblock %}
        <script>check_is_in_favourites_and_cart({{ user.get_fav_list }}, {{ user.get_cart_list }})</script>
    </main>
</body>
</html>